version: "3.4"

x-defaults: &default
  restart: unless-stopped
#  使用当前目录的 Dockerfile 来构建 docker 镜像
  build: .
  volumes:
# 把当前目录(源代码目录) mount 到 docker container 的特定目录，那个目录就是 docker 环境里面进行编译的工作区间
    - .:/home/deploy/projects/
  networks:
    - default

services:
  projects-dev:
    <<: *default
    container_name: projects-dev
    hostname: "projects"
    user: deploy
    working_dir: /home/deploy/projects
#   需要改变 security_opt， 不然 gdb server 会跑不起来
    security_opt:
      - seccomp:unconfined
#   开启 ssh 服务，这样 clion 就能通过 ssh 连接进来了
#   同时通过 tailf 命令保持 container 不要退出的状态
    command:
      bash -c "sudo service ssh restart && tail -f /dev/null"
    ports: 
      - "2222:22"

# 手动配置网络， 这样就有固定的 ip 了
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.129.2.0/24
